services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
        - "8080:8080"
  status-service:
    image: status-service
    build:
      context: status-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
  receiver-service:
    depends_on:
      - keycloak
    image: receiver-service
    build:
      context: receiver-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
