services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      debug: true
    ports:
      - "5672:5672"
      - "15672:15672"
  status-service:
    image: status-service
    build:
      context: status-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
  receiver-service:
    image: receiver-service
    build:
      context: receiver-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
