server:
  port: 8081
spring:
  application:
    name: receiver-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/receive-rest
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
jwt:
  auth:
    converter:
      principal-attribute: username
      resource-id: receiver-rest-api